# Generated by Django 3.0.7 on 2020-08-04 05:44

from django.db import migrations, models
import django.db.models.deletion

GCHAT_SPACE_BECOMES_MANY_TO_MANY = """
    INSERT INTO group_gchat_spaces(group_id, gchat_space_id)
    SELECT g.id, g.gchat_space_id FROM groups g
    WHERE g.gchat_space_id is not null
"""
class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0034_auto_20200728_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGchatSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gchat_space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discussions.GchatSpace')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discussions.Group')),
            ],
            options={
                'db_table': 'group_gchat_spaces',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='gchat_spaces',
            field=models.ManyToManyField(blank=True, help_text="Charcha will regularly import members from this chat room. By default, each member will have the role 'member'. You can override the role for any member in the group settings screen.", null=True, through='discussions.GroupGchatSpace', to='discussions.GchatSpace', verbose_name='Google Chat Room'),
        ),
        migrations.RunSQL(GCHAT_SPACE_BECOMES_MANY_TO_MANY),
        migrations.RemoveField(
            model_name='group',
            name='gchat_space',
        ),

    ]
