# Generated by Django 3.0.7 on 2020-08-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0035_auto_20200804_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='gchat_spaces',
            field=models.ManyToManyField(blank=True, help_text="Charcha will regularly import members from this chat room. By default, each member will have the role 'member'. You can override the role for any member in the group settings screen.", through='discussions.GroupGchatSpace', to='discussions.GchatSpace', verbose_name='Google Chat Room'),
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together={('submission_time',), ('last_modified',), ('last_activity',)},
        ),
    ]
