# Generated by Django 3.0.7 on 2020-08-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0037_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slide_object_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
