# Generated by Django 3.0.7 on 2020-08-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0038_userprofile_slide_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slide_object_id',
        ),
    ]
