# Generated by Django 3.0.7 on 2020-08-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0039_remove_userprofile_slide_object_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
